# Generated by Django 3.0.6 on 2020-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('slug', models.URLField()),
                ('description', models.TextField()),
                ('screenshot_link_1', models.URLField(blank=True, null=True)),
                ('screenshot_link_2', models.URLField(blank=True, null=True)),
                ('screenshot_link_3', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
