# Generated by Django 3.0.6 on 2020-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='google_play_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
