# Generated by Django 3.0.6 on 2020-05-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_app_google_play_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='developer_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
