# Generated by Django 3.0.6 on 2020-05-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_app_developer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ratings',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
