# Generated by Django 3.0.6 on 2020-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_app_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='slug',
            new_name='url',
        ),
        migrations.AddField(
            model_name='app',
            name='androidVersion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='release_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='review_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='review_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='review_3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
